name: tic_tac_toe_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_close_app: ^1.0.0
  google_fonts: ^6.2.1
  page_transition: ^2.1.0
  popover: ^0.3.0+1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/profile.png
    - lib/assets/medal.png
    - lib/assets/lose.png
    - lib/assets/scoreboard-tied.png
